version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3333:81"
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "1880:3000"  # Порт 1880 на хосте мапится на порт 3000 в контейнере
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://localhost:3333 # Или http://backend:80, если хотите обращаться через внутреннюю сеть Docker
    volumes:
      - ./frontend:/app # Монтируем папку frontend для горячей перезагрузки